gpus: '0'
model: 'scdgc'
loss: 'BCElogitloss'
lam: 0.1
word_embedding: False
correlation_dim: 128
time_step: 6
pretrain_backbone: './initmodels/resnet101.pth'
optimizer: 'AdamW'
lr: 1e-4
weight_decay: 1e-2
ema_decay: 0.9997
image_size: 448
num_workers: 8
batch_size: 64
start_test: 10
max_epoch: 80
warm_up_epoch: 0
topk: 3
threshold: 0.5
log_dir: './logs'
ckpt_dir: './checkpoints'
ckpt_latest_path: './checkpoints/latest_model.pth'
ckpt_best_path: './checkpoints/best_model.pth'
parallel: True
transform2: True